---
execute:
  freeze: auto
  eval: true
---

```{r setup, include=FALSE, eval=TRUE}
## Setting up
 pacman::p_load(arrow, here, tidyverse, janitor, purrr, dplyr)

# Load helper functions
source(here("R/utils.R"))

# Load cleaned data (includes citizen science data)
myg_spiders_cleaned <- read_parquet(get_latest_cleaned_data(path_to_clean_data = paste0(here("output/data/"), "/"))[2])

# Load cleaned expert data 
myg_spiders_cleaned_expert <- read_parquet(get_latest_cleaned_data(path_to_clean_data = paste0(here("output/data/"), "/"))[1])

```

# Discussion

Globally, but particularly in Australia, invertebrates suffer from a paucity of ecological knowledge, which hinders their management and conservation [@new12; @taylor18]. Landscape approaches such as habitat protection are a key principal of conservation, helping to protect species and ecological communities from broadscale threats [@samways07; @kearney18]. Despite this, invertebrates are rarely considered in the designation of protected areas [@chowdhury23]. Prioritizing biodiversity hotspots in spatial conservation planning will enhance the effectiveness of protected areas for biodiversity conservation. The identification and management of endemism hotspots, i.e. areas where range-restricted species are concentrated, is an important strategy for curbing the likely high rate of invertebrate extinctions in Australia [@woinarski24]. Our analytical framework is a useful tool for identifying these hotspots and can be applied to different taxonomic groups. 

Bit about spiders

For Mygalomorph spiders, two main hotspots of species richness and weighted endemism were identified and were highly congruent across the two datasets: a large cluster centred around Brisbane, spanning south-east Queensland and north-east New South Wales, and another centred around Cairns in the Wet Tropics of Queensland. Corrected weighted endemism was clustered in different hotspots, and there were some discrepancies between the datasets. Both datasets revealed a large hotspot in south-west Western Australia, although this hotspot was of a larger extent in the preserved specimen only dataset. Both datasets also showed a hotspot in far north Queensland at the end of the Cape York Peninsula, as well as a small hotspot in central Australia near the Warburton Range. The preserved specimen only dataset also showed a small cluster located between Canberra and Sydney in New South Wales. The large hotspots identified, i.e. south-east Queensland/north-east New South Wales; Wet Tropics; and south-west Western Australia, align with internationally recognised [global biodiversity hotspots](https://www.conservation.org/priorities/biodiversity-hotspots): the Forests of East Australia, and the Southwest Australia Ecoregion [@mittermeier11]. This provides further support for the need for conservation of these areas, which are predominantly recognised for their plant and vertebrate fauna diversity [@myers00]. These global biodiversity hotspots are recognised as having lost at least 70% of their original natural vegetation [@mittermeier11], highlighting that the hotspots we have identified for Mygalomorph spiders may face similar threats. The hotspots we identified also align closely with hotspots of vascular plant richness and endemism identified by @crisp01, including the hotspot at the tip of Cape York. Cape York is recognised as a major region of transition between the biota of Australia and Papua New Guinea, which were connected as a continuous land mass around 21000 years BP [@williams93]. The endemism in this area may therefore be reduced if the analysis was extended to include adjacent countries such as Papua New Guinea. The hotspot we identified near Brisbane encapsulates the Border Ranges at the border between Queensland and New South Wales, where the climate and geography facilitate the co-occurrence of temperate and tropical species, including a high number of endemics [@burbidge60].

There were marked discrepancies in the hotspots identified by the two endemism metrics. Corrected weighted endemism accounts for species richness, thereby preventing areas being identified as hotspots of endemism simply because they have more species overall [@crisp01]. However, this then risks important endemics being masked by the influence of species richness in cases where short-range species exist in areas of high species richness. @shipley22 therefore advocate in favour of weighted endemism when the focus is on identification and conservation of endemism hotspots. Our results highlight the discrepancy between the methods, and show that using a variety of metrics can help identify different areas of interest. For example, weighted endemism on its own would have overlooked the hotspot in south-west Western Australia, which is characterised by a higher proportion of short-range endemics, despite being less species rich than the hotspots in north-eastern Australia.

Another caveat of the methods is that small hotspots may not be picked up in the spatial autocorrelation analysis. Moran’s I is useful for identifying clusters of similar spatial units but small hotspots may be missed due to the spatial scale of the analysis or sampling bias, i.e. if a high endemism area is restricted to a single grid cell and not correlated with surrounding cells (maybe surrounding cells have not been sampled) then it will not be highlighted by local Moran’s I. These cells can still be identified for further investigation using the maps of the respective biodiversity metrics. The size of spatial units can be adjusted, however this should be considered carefully as spatial patterns in metrics are influenced by the designation of spatial units (the Modifiable Areal Unit Problem (MAUP); @jelinski96). 

When applying this analytical framework, the characteristics of the target taxon should be considered, such as the distinctiveness of constituent species and the potential for errors in identification. This will affect the choice of whether to include citizen science data in the analysis. For Mygalomorph spiders, there was a high degree of congruence between the hotspots identified using the two datasets (full dataset and preserved specimen (expert) only), indicating that the citizen science records did not change the broad patterns of biodiversity. Citizen science data may be more influential for taxa that have a higher proportion of records from citizen science sources (`r round((nrow(myg_spiders_cleaned) - nrow(myg_spiders_cleaned_expert))/nrow(myg_spiders_cleaned)*100, digits = 0)`% for Mygalomorphae). In cases where there are discrepancies between datasets, rather than being discounted, citizen science data can identify potential areas of interest, where further investigation and expert resources can be directed.

Efforts to increase the knowledge base of invertebrate ecology in Australia, such as increased monitoring of invertebrate populations, along with taxonomic research, will improve hotspot identification and conservation.
