# Introduction

<!-- Beautiful start to the report! Well done Josh! -->

Invertebrates are an often overlooked but vital component of healthy ecosystems. They perform a variety of critical ecological functions and ecosystem services, including pollination, soil modification, organic matter decomposition, nutrient cycling, pest control, and food provisioning to other animals and humans @lavelle06, @macadam15, @griffiths21, @porto21. They are ubiquitous across land and seascapes, constituting the vast majority of Earth's biodiversity. Over 1.25 million invertebrate species have been documented, representing around 95% of animal species @eisenhauer21. However, many invertebrate species and populations around the globe are under threat, as are the services they provide and the ecosystems they support @hallmann17, @ulrich2020, @wagner21, @eisenhauer23. 

<!-- Can we introduce some Australian stats here? See https://soe.dcceew.gov.au/biodiversity/environment/flora-and-fauna -->
Australia has a high proportion of endemic fauna and is home to around 320,000 invertebrate species, of which around 35% have been described @murphy21. These include invertebrates of cultural significance to Indigenous Australians, such as freshwater crayfish (marron), beetle larvae (witchetty grubs), and Bogong moths, used for food, medicine, and ceremonies for thousands of years @faast20 @stephenson20 @murphy21. Invertebrates also play vital roles in Australian agriculture, land management, and environmental monitoring @andersen04, @holloway08. Despite their ecological, cultural, social, and economic importance, invertebrates are often neglected in conservation and management plans, and a lack of taxonomic and ecological knowledge hinders their protection @braby18, @braby19, @sands18. Invertebrates constitute 95% of Australia's faunal diversity but only 15% of species assessed under the Environment Protection and Biodiversity Conservation Act (EPBC Act), and only around 480 species of Australian invertebrates are listed as threatened (invertebratesaustralia.org).

Invertebrates face a multitude of anthropogenic and environmental threats, including habitat loss, climate change (and associated events such as fires, floods, and droughts), pollution, pesticides, and introduced species @wagner21, @marsh22, @reddin22. There is growing evidence that such pressures, which have seen widespread invertebrate declines around the globe, are impacting Australian species @braby21. While there is an urgent need for further research on invertebrate biodiversity and conservation in relation to these threats, conservation measures can help to mitigate their effects, protect and restore biodiversity, and prevent extinctions.

Biological conservation is hampered by limited resources, and identifying priority areas to focus conservation efforts can help to maximise their effectiveness @myers00. Species richness and endemism are key indices of biodiversity that reflect biological complexity and uniqueness, and can be used to identify 'biodiversity hotspots' to prioritise for conservation @myers88 @caldecott96, @reid98. **Species richness refers to the number of species in an area**. Numerous definitions of **endemism exist but generally a taxon is considered endemic to a particular area if it occurs only in that area @anderson94**. By these definitions, species richness and endemism are dependent on spatial scale @townsendpeterson. Quantifying endemism and identifying areas of high endemism is important in conservation because narrowly endemic taxa have small ranges by definition and are therefore more vulnerable to threats such as habitat loss and climate change @harvey11. The 10 known invertebrate extinctions in Australia are all narrow-range endemics @braby19. There is a need to identify hotspots of invertebrate biodiversity to enhance their conservation, particularly within Australia @taylor18. Designation of protected areas and other landscape management practices can be informed by spatial quantification of endemism. Identifying hotspots helps to focus limited resources and improve the efficiency of biodiversity conservation efforts.

Identifying hotspots for all invertebrates is not logistically feasible at present, so as a proof of concept we focussed on spiders in the infraorder _Mygalomorphae_, using spatial analyses to identify hotspots of species richness and endemism across Australia. Mygalomorph spiders have poor dispersal capabilties and sedentary habits, making them well-suited to endemism analyses @ferretti14. Australian mygalomorphs are diverse and many may face a greater level of threat than what is formally recognised @castalanelli14, @rix17. Our methods can be used as a framework and extended to other taxonomic groups. Identifying hotspots of endemism in the Australian invertebrate fauna will help guide research and conservation efforts and improve outcomes, not only for invertebrates, but for the ecological communities they support.

 <!-- I think we can move this nitty gritty stuff to the Statistical analyses/Endemism section -->
(to move to methods)
Quantification of endemism depends on the spatial scale being considered, and numerous calculation methods exist (). Endemism can be quantified on a continuous scale across a spatial grid with reference to the constituent grid cells, based on how many cells taxa occupy.