---
title: "Spatial bias"
author: "Josh Nitschke"
date: "2024-04-06"
output: 
  rmdformats::downcute:
    self_contained: true
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---

<style>
#toc ul.nav li ul li {
    display: none;
    max-height: none;
}

#toc ul.nav li.active ul li  {
    display: block;
    max-height: none;
}

#toc ul.nav li ul li ul li {
    max-height: none;
    display: none !important;
}

#toc ul.nav li ul li.active ul li {
    max-height: none;
    display: block !important;
}
</style>


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadpackages, include=FALSE}
## Setting up

# install.packages("pacman")
pacman::p_load(galah, arrow, here, tidyverse, janitor, ozmaps, sf, ggplot2, wesanderson, dplyr, DT, sampbias, viridis)

# Load helper functions
source(here("R/utils.R"))

## Read in parquet
myg_spiders_all <- open_dataset(here(get_latest_download()))

## Subset columns we want for ALA data overview
myg_spiders_spatial_bias <- myg_spiders_all |> 
  select(species, decimalLatitude, decimalLongitude, recordID) |> 
  collect()
```

Making a map of Australia

```{r}
# map of Australia with states
aus <- st_transform(ozmaps::ozmap_states, 4326)

## check map
ggplot(aus) + geom_sf(fill = "transparent")
```

modelling spatial sampling bias

```{r}
model_bias_myg <- sampbias::calculate_bias(
  x = myg_spiders_spatial_bias,
  res = 0.05,   # scale of spatial resolution
  buffer = 0.5, # account for neighbouring features
  restrict_sample = sf:::as_Spatial(aus)
)
```

