---
title: "02_ala_data_overview_mygalomorph"
author: "Josh Nitschke"
date: "2023-09-19"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load dependencies

```{r loadpackages}
# install.packages("pacman")
pacman::p_load(galah, arrow, here, tidyverse, janitor, ozmaps, sf, ggplot2, wesanderson, dplyr)

```

## Read in parquet

```{r}
myg_spiders_all <- open_dataset(here("data/galah/Mygalomorphae_withassertions2023-09-01_ALA.paraquet"))
```

## Subset columns we want for ALA data overview

```{r}
myg_spiders <- myg_spiders_all |> 
  select(decimalLatitude:collectionCode) |> 
  collect()
```

### Data Overview

How many species in dataset

```{r}
myg_spiders |> 
  group_by(taxonRank) |> 
  summarise(n = n())

# how many records for each species with at least three records
myg_spp <- myg_spiders |>
  filter(!is.na(species)) |>
  group_by(species) |>
  filter(n() > 2) |>
  tabyl(species) |>
  arrange(desc(n))
myg_spp

# Plot of records for each species
myg_spp_df <- as.data.frame(myg_spp)
barplot(myg_spp_df$n, xlab = "species", ylab = "records")

# How many species have at least three records
nrow(myg_spp)

# number of species in each family
myg_fams <- myg_spiders |>
  filter(!is.na(species)) |>
  group_by(species) |>
  #filter(n() > 2) |>
  group_by(family, species) |>
  summarise(n = n()) |>
  tabyl(family) |>
  arrange(desc(n))

as.data.frame(myg_fams)|>
  mutate(family = factor(family, levels = family))|>
  ggplot(aes(x = family, y = n)) +
  geom_bar(stat = "identity") +
  labs(y = "number of species") +
  theme_minimal() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 90, colour = "black"),
        axis.text.y = element_text(colour = "black"),
        axis.line = element_line(colour = "black"))
#which families are not represented?

# Why are these unranked? Selenocosmia crassipes AB to ask colleagues and JM 
myg_spiders |> 
  filter(taxonRank == "unranked") |> 
  select(scientificName, collectionCode) |> 
  distinct()

```

### Species overview by state

```{r}
# number of records by state, for species with at least three overall records
myg_records_by_state <- myg_spiders |>
  filter(!is.na(species)) |>
  group_by(species) |>
 # filter(n() > 2) |>
  group_by(stateProvince, species) |>
  summarise(n()) 
myg_records_by_state

# number of species by state, for species with at least three overall records
myg_spp_by_state <- myg_records_by_state |> 
  tabyl(stateProvince) |>
  arrange(desc(n))

# number of families by state
myg_fam_by_state <- myg_spiders |>
  filter(!is.na(species)) |>
  group_by(species) |>
 # filter(n() > 2) |>
  group_by(stateProvince, family) |>
  summarise(n()) |>
  tabyl(stateProvince) |>
  arrange(desc(n))

#plotting numbers of species and families by state
myg_spp_fam_by_state <- left_join(myg_spp_by_state, myg_fam_by_state, by = "stateProvince")

scale_right <- max(myg_spp_fam_by_state$n.y)/max(myg_spp_fam_by_state$n.x)

as.data.frame(myg_spp_fam_by_state)|>
  mutate(stateProvince = factor(stateProvince, levels = stateProvince))|>
  ggplot(aes(x = stateProvince)) +
  geom_bar(stat = "identity", aes(y = n.x, fill = "species")) +
  geom_bar(stat = "identity", aes(y = n.y/scale_right, fill = "families"), colour = "black", alpha = 0.5) +
  scale_y_continuous(sec.axis = sec_axis(~.*scale_right, name = "number of families")) + 
  scale_fill_manual(values = c("grey30", "lightgreen")) +
  labs(y = "number of species") +
  theme_minimal() +
  theme(panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        axis.text.x = element_text(angle = 90, colour = "black"),
        axis.text.y = element_text(colour = "black"),
        axis.line = element_line(colour = "black"))

#checking records where stateProvince = NA but still have lat/long
myg_spiders_na_state <- myg_spiders |>
  filter(is.na(stateProvince)) |>
  filter(!is.na(decimalLatitude))

aus <- st_transform(ozmaps::ozmap_country, 4326)

ggplot() + 
  geom_sf(data = aus, 
          colour = "black", 
          fill = "white")  + 
   geom_point(data = myg_spiders_na_state, 
             mapping = aes(decimalLongitude, decimalLatitude), 
             colour = "red", size = 0.8) + 
  # coord_sf(xlim=c(135, 155), 
  #          ylim=c(-10, -32)) +
  labs(title = "myg_spiders: stateProvince = NA", 
       x = "Longtitude (DD)", 
       y = "Latitude (DD)") +
  theme_bw()

# number of species recorded in only one state (species with at least three overall records)
myg_spp_by_state |> 
  filter(n == 1) |>
  nrow()

# number of species recorded in more than one state (species with at least three overall records)
myg_spp_by_state |> 
  filter(n > 1) |>
  nrow()

```

## Basis of record
```{r}
myg_spiders |>
  filter(!is.na(species)) |>
  tabyl(basisOfRecord) |>
  arrange(desc(n))

# Exclude, can't trace back to source
myg_spiders |> 
  filter(basisOfRecord == "OCCURRENCE") |> 
  select(ends_with("code"
  ))


myg_spiders |> 
  filter(basisOfRecord == "OBSERVATION") |> 
    select(ends_with("code"
  ))

# Machine observe keep the one with spatial data
myg_spiders |> 
  filter(basisOfRecord == "MACHINE_OBSERVATION", 
         taxonRank == "species") |> 
  select(scientificName, recordID, starts_with("decimal"))

```

### Overview of assertions

```{r}
myg_assertions <- myg_spiders_all |> 
  dplyr::select(scientificName, taxonRank, species, decimalLatitude:decimalLongitude, recordID, collectionCode, institutionCode,  AMBIGUOUS_COLLECTION:ZERO_COORDINATE) |> 
  collect()

myg_assertions

myg_assertions_long <- myg_assertions |>
  pivot_longer(cols = c(AMBIGUOUS_COLLECTION:ZERO_COORDINATE), names_to = "assertion_type", values_to = "value") 

assertion_counts <- myg_assertions_long |>
  filter(value == TRUE) |>
  tabyl(assertion_type)

# Join with ala_assertions.csv so we have summary of counts
asserts <- read_csv(here("output/ala_assertions.csv"))
# asserts |> 
#   left_join(assertion_counts, by = join_by(id == assertion_type)) |>
#   arrange(-n) |> 
#   write_csv(here("output/ala_assertions_with_counts.csv"))

#Filtering observations where all assertions are false
myg_assertions |>
  filter(!if_any(AMBIGUOUS_COLLECTION:ZERO_COORDINATE))
```

### Checking coordinate-related assertions
```{r}
myg_assertions |>
  filter(!is.na(species),
         !is.na(decimalLatitude),
         !is.na(decimalLongitude)) |>
  filter(if_any(starts_with("COORDINATE"))) |>
  group_by(species) |>
  tabyl(species) |>
  arrange(desc(n))

# plotting spp. with the most flagged records for coordinate-based assertions
myg_spp_coordinate_assertions <- myg_assertions |>
  filter(!is.na(species),
         !is.na(decimalLatitude),
         !is.na(decimalLongitude)) |>
  filter(if_any(starts_with("COORDINATE"))) |>
  group_by(species) |>
  filter(n() > 100)

aus <- st_transform(ozmaps::ozmap_states, 4326)

ggplot() + 
  geom_sf(data = aus, 
          colour = "black", 
          fill = "white")  + 
   geom_point(data = myg_spp_coordinate_assertions, 
             mapping = aes(decimalLongitude, decimalLatitude, colour = species), 
             size = 0.8) + 
  # coord_sf(xlim=c(135, 155), 
  #          ylim=c(-10, -32)) +
  labs(title = "myg_spiders: assertions starting with 'COORDINATE' = TRUE", 
       x = "Longtitude (DD)", 
       y = "Latitude (DD)") +
  theme_bw()

```


```{r}
coord_invalid <- myg_assertions |>
  select(species, decimalLatitude, decimalLongitude, COORDINATE_INVALID)

coord_invalid_spp <- coord_invalid |>
  group_by(species) |>
  summarise(num_true = sum(COORDINATE_INVALID)) |>
  filter(num_true > 0) |>
  pull(species)

coord_invalid_spp_no_na <- myg_assertions |>
  filter(species %in% coord_invalid_spp,
         !is.na(species))

  ggplot() + 
  geom_sf(data = aus, 
          colour = "black", 
          fill = "white")  + 
   geom_point(data = coord_invalid_spp_no_na, mapping = aes(decimalLongitude, decimalLatitude, colour = COORDINATE_INVALID), 
             size = 0.8, alpha = 0.5) + 
  # coord_sf(xlim=c(135, 155), 
  #          ylim=c(-10, -32)) +
  labs(title = "myg_spiders: coordinate_invalid", 
       x = "Longtitude (DD)", 
       y = "Latitude (DD)") +
  theme_bw() +
    facet_wrap(~species)
  
coord_invalid_spp_no_na |>
  filter(COORDINATE_INVALID == TRUE)
```

get verbatum coordinates
```{r}
miss_occ_coord_flagged <- myg_assertions |>
  filter(species == "Missulena occatoria") |>
  select(species, decimalLatitude, decimalLongitude, contains("COORDINATE")) |>
  pivot_longer(cols = contains("COORDINATE"), names_to = "assertion_type", values_to = "assertion_flag") |>
  filter(assertion_flag == TRUE) 

ggplot() + 
  geom_sf(data = aus, 
          colour = "black", 
          fill = "white")  + 
   geom_point(data = miss_occ_coord_flagged, mapping = aes(decimalLongitude, decimalLatitude, colour = assertion_type), 
             size = 1.5) + 
  scale_colour_manual(values = wes_palette("BottleRocket2")) +
  # coord_sf(xlim=c(135, 155), 
  #          ylim=c(-10, -32)) +
  labs(title = "myg_spiders: miss_occ_coord_flagged", 
       x = "Longtitude (DD)", 
       y = "Latitude (DD)") +
  theme_bw() +
  facet_wrap(~assertion_type)

```


