---
title: "Alpha hulls"
author: "Fonti Kar and Payal Bal"
date: "2023-08-25"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadpackages}
# Install the package
#install.packages("remotes")
# remotes::install_github("beatrizpateiro/alphahull", ref="WIP-ahull.IUCN-feature")
# remotes::install_github("babichmorrowc/hull2spatial")
# remotes::install_github("gdauby/ConR")

# Load packages
#install.packages("pacman")
pacman::p_load(galah, arrow, here, tidyverse, ozmaps, sf, ggplot2, skimr, alphahull, hull2spatial, sp, purrr, ConR, dplyr)


source("R/utils.R")
```

## Read in data

```{r}
get_latest_cleaned_data()

myg_spiders_cleaned <- read_parquet(get_latest_cleaned_data(path_to_clean_data = paste0(here("output/data/"), "/"))[2])

myg_spiders_expert <- read_parquet(get_latest_cleaned_data(path_to_clean_data = paste0(here("output/data/"), "/"))[1])

myg_spiders_hum_obs <- myg_spiders_cleaned |>
  filter(basisOfRecord == "HUMAN_OBSERVATION")
```

# All data 
## Create an alpha hull

Alpha hulls are a flexible way to represent species distributions without all the extra work of running a species distribution model. 


#### Extrapolate to all Myg taxa

```{r}
# A function to generate alpha-hull and extract output and transform into sf object
ConR_ahull <- function(data, sf_transform = TRUE){

  conr_output <- ConR::EOO.computing(data, 
                               method.range = "alpha",
                               alpha = 2, 
                               buff.alpha = 0.000001,
                               export_shp = TRUE)
  if(sf_transform == TRUE){
  as(conr_output$spatial, "Spatial")
  } 
  else
    conr_output$spatial
}

# Nest data
myg_conr_nest <- myg_spiders_cleaned |> 
  dplyr::select(decimalLatitude, decimalLongitude, scientificName, eventDate) |> 
  mutate(species = scientificName) |> 
  nest(occ = c(starts_with("decimal"), scientificName, eventDate))

# Test function on one
test <- ConR_ahull(myg_conr_nest$occ[[1]], sf_transform = TRUE)


# A function to map over
#Can't get this map working for some reason!
myg_conr_nest <- myg_conr_nest |>
  mutate(conr_ahull = purrr::map(.x = occ,
                          possibly(~ConR_ahull(.x))
  ),
  conr_ahull_sf =  purrr::map(.x = occ,
                          possibly(~ConR_ahull(.x, FALSE))
  )) 
```

### Drop empty polygons

```{r}
myg_conr_nest |> 
  print(n = Inf)

x <- myg_conr_nest |> 
  purrr::map(discard, .p = is.null) |> 
  tibble()

null_spdf <- myg_conr_nest$conr_ahull |> 
  purrr::map(is.null) |> 
  list_c() |> which()

myg_conr_nest |> 
  # filter(row_number() %in% null_spdf) |> 
  pluck("occ", 2)
```

### Alpha hulls as sf to plot all on a map

```{r}
# Transform projection
aus <- st_transform(ozmaps::ozmap_country, 4326)

# Base map 
base_map <- ggplot() + 
  geom_sf(data = aus, fill = NA, colour = "black") + 
  theme_minimal()

# add the points as sf for species without alpha hulls (< 3 records)
myg_conr_nest_points <- myg_conr_nest |>
    mutate(
    conr_ahull_sf = map2(conr_ahull_sf, occ, ~{
      if (is.null(.x)) {
        # Convert occ tibble into sf POINTS
        pts <- st_as_sf(.y, coords = c("decimalLongitude", "decimalLatitude"), crs = 4326)
        # Collapse all points into a MULTIPOINT
        st_union(pts) |> st_cast("MULTIPOINT")
      } else {
        sf::st_geometry(.x) |>
        sf::st_cast("MULTILINESTRING") |> # to get filled polygons instead of just the boundaries
        sf::st_polygonize()
      }
    })
  )

#Unnest the sf
all_myg_alpha_sf_points <- myg_conr_nest_points |> 
  dplyr::select(species, conr_ahull_sf) |> 
  tidyr::unnest(cols = c(conr_ahull_sf)) |> 
  sf::st_as_sf()

# crop to land area only
all_myg_alpha_sf_land <- st_intersection(all_myg_alpha_sf_points, aus)

# separating polygons and points for plotting
polys <- all_myg_alpha_sf_land |>
  filter(st_geometry_type(conr_ahull_sf) %in% c("POLYGON", "MULTIPOLYGON"))
points <- all_myg_alpha_sf_land |>
  filter(st_geometry_type(conr_ahull_sf) %in% c("POINT", "MULTIPOINT"))

# plotting alpha hulls and points
base_map  + 
  geom_sf(data = polys, 
          aes(geometry = conr_ahull_sf),
           # colour = "black",
          colour = "#609966",
          fill = "lightgreen") +
  geom_sf(data = points,
             aes(geometry = conr_ahull_sf),
             colour = "red",
             fill = "red") +
  coord_sf(c(110, 155)) +
  theme_minimal() |> 
  theme(legend.position = "none")

```

#### Save output as rds for next step of workflow

```{r}
# Save output

get_latest_cleaned_data()

# Clean up the name
file_name <- str_split_1(get_latest_cleaned_data(path_to_clean_data = paste0(here("output/data/"), "/"))[2], "/")[10] |> str_remove(".parquet")

saveRDS(all_myg_alpha_sf_land, here("output/spatial", paste0("Spatial_alpha_hulls_sf_class_", file_name, ".rds")))
```

# Expert Only data

```{r}
# Nest data
myg_conr_nest_ex <- myg_spiders_expert |> 
  dplyr::select(decimalLatitude, decimalLongitude, scientificName, eventDate) |> 
  mutate(species = scientificName) |> 
  nest(occ = c(starts_with("decimal"), scientificName, eventDate))

# A function to map over
#Can't get this map working for some reason!
myg_conr_nest_ex <- myg_conr_nest_ex |>
  mutate(conr_ahull = purrr::map(.x = occ,
                          possibly(~ConR_ahull(.x))
  ),
  conr_ahull_sf =  purrr::map(.x = occ,
                          possibly(~ConR_ahull(.x, FALSE))
  )) 
```

```{r}
# add the points as sf for species without alpha hulls (< 3 records)
myg_conr_nest_ex_points <- myg_conr_nest_ex |>
    mutate(
    conr_ahull_sf = map2(conr_ahull_sf, occ, ~{
      if (is.null(.x)) {
        # Convert occ tibble into sf POINTS
        pts <- st_as_sf(.y, coords = c("decimalLongitude", "decimalLatitude"), crs = 4326)
        # Collapse all points into a MULTIPOINT
        st_union(pts) |> st_cast("MULTIPOINT")
      } else {
        sf::st_geometry(.x) |>
        sf::st_cast("MULTILINESTRING") |> # to get filled polygons instead of just the boundaries
        sf::st_polygonize()
      }
    })
  )

#Unnest the sf
all_myg_alpha_sf_points_ex <- myg_conr_nest_ex_points |> 
  dplyr::select(species, conr_ahull_sf) |> 
  tidyr::unnest(cols = c(conr_ahull_sf)) |> 
  sf::st_as_sf()

# crop to land area only
all_myg_alpha_sf_land_ex <- st_intersection(all_myg_alpha_sf_points_ex, aus)

# separating polygons and points for plotting
polys_ex <- all_myg_alpha_sf_land_ex |>
  filter(st_geometry_type(conr_ahull_sf) %in% c("POLYGON", "MULTIPOLYGON"))
points_ex <- all_myg_alpha_sf_land_ex |>
  filter(st_geometry_type(conr_ahull_sf) %in% c("POINT", "MULTIPOINT"))

# plotting alpha hulls and points
base_map  + 
  geom_sf(data = polys_ex, 
          aes(geometry = conr_ahull_sf),
           # colour = "black",
          colour = "#609966",
          fill = "lightgreen") +
  geom_sf(data = points_ex,
             aes(geometry = conr_ahull_sf),
             colour = "red",
             fill = "red") +
  coord_sf(c(110, 155)) +
  theme_minimal() |> 
  theme(legend.position = "none")

```

```{r}
# Save output
# Clean up the name
file_name <- str_split_1(get_latest_cleaned_data(path_to_clean_data = paste0(here("output/data/"), "/"))[1], "/")[10] |> str_remove(".parquet")

saveRDS(all_myg_alpha_sf_land_ex, here("output/spatial", paste0("Spatial_alpha_hulls_sf_class_expert_", file_name, ".rds")))
```


# Human obs Only data

```{r}
# Nest data
myg_conr_nest_hum_obs <- myg_spiders_hum_obs |> 
  dplyr::select(decimalLatitude, decimalLongitude, scientificName, eventDate) |> 
  mutate(species = scientificName) |> 
  nest(occ = c(starts_with("decimal"), scientificName, eventDate))

# A function to map over
#Can't get this map working for some reason!
myg_conr_nest_hum_obs <- myg_conr_nest_hum_obs |>
  mutate(conr_ahull = purrr::map(.x = occ,
                          possibly(~ConR_ahull(.x))
  ),
  conr_ahull_sf =  purrr::map(.x = occ,
                          possibly(~ConR_ahull(.x, FALSE))
  )) 
```

```{r}
# add the points as sf for species without alpha hulls (< 3 records)
myg_conr_nest_hum_obs_points <- myg_conr_nest_hum_obs |>
    mutate(
    conr_ahull_sf = map2(conr_ahull_sf, occ, ~{
      if (is.null(.x)) {
        # Convert occ tibble into sf POINTS
        pts <- st_as_sf(.y, coords = c("decimalLongitude", "decimalLatitude"), crs = 4326)
        # Collapse all points into a MULTIPOINT
        st_union(pts) |> st_cast("MULTIPOINT")
      } else {
        sf::st_geometry(.x) |>
        sf::st_cast("MULTILINESTRING") |> # to get filled polygons instead of just the boundaries
        sf::st_polygonize()
      }
    })
  )

#Unnest the sf
all_myg_alpha_sf_points_hum_obs <- myg_conr_nest_hum_obs_points |> 
  dplyr::select(species, conr_ahull_sf) |> 
  tidyr::unnest(cols = c(conr_ahull_sf)) |> 
  sf::st_as_sf()

# crop to land area only
all_myg_alpha_sf_land_hum_obs <- st_intersection(all_myg_alpha_sf_points_hum_obs, aus)

# separating polygons and points for plotting
polys_hum_obs <- all_myg_alpha_sf_land_hum_obs |>
  filter(st_geometry_type(conr_ahull_sf) %in% c("POLYGON", "MULTIPOLYGON"))
points_hum_obs <- all_myg_alpha_sf_land_hum_obs |>
  filter(st_geometry_type(conr_ahull_sf) %in% c("POINT", "MULTIPOINT"))

# plotting alpha hulls and points
base_map  + 
  geom_sf(data = polys_hum_obs, 
          aes(geometry = conr_ahull_sf),
           # colour = "black",
          colour = "#609966",
          fill = "lightgreen") +
  geom_sf(data = points_hum_obs,
             aes(geometry = conr_ahull_sf),
             colour = "red",
             fill = "red") +
  coord_sf(c(110, 155)) +
  theme_minimal() |> 
  theme(legend.position = "none")

```

```{r}
# Save output
# Clean up the name
file_name <- str_split_1(get_latest_cleaned_data(path_to_clean_data = paste0(here("output/data/"), "/"))[1], "/")[10] |> str_remove(".parquet")

saveRDS(all_myg_alpha_sf_land_hum_obs, here("output/spatial", paste0("Spatial_alpha_hulls_sf_class_human_obs_", file_name, ".rds")))
```