---
title: "Protected area overlap with hotspots"
author: "Fonti Kar and Payal Bal"
date: "2023-08-25"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadpackages}
# Install the package
#install.packages("remotes")
# remotes::install_github("beatrizpateiro/alphahull", ref="WIP-ahull.IUCN-feature")
# remotes::install_github("babichmorrowc/hull2spatial")
# remotes::install_github("gdauby/ConR")

# Load packages
#install.packages("pacman")
pacman::p_load(galah, arrow, here, tidyverse, ozmaps, sf, ggplot2, skimr, alphahull, hull2spatial, sp, purrr, ConR, dplyr, wdpar, ggmap, terra, raster)


source("R/utils.R")
```

## Downloading protected area data for Australia
```{r}
# aus_raw_pa_data <- wdpa_fetch(
#   "Australia", wait = TRUE, download_dir = rappdirs::user_data_dir("wdpar")
# )
# 
# # clean PA data
# aus_pa_data <- wdpa_clean(aus_raw_pa_data)
# 
# saveRDS(aus_pa_data, here("data/protected_areas/aus_pa_data.rds"))

aus_pa_data <- readRDS(here("data/protected_areas/aus_pa_data.rds"))
```

## clipping PA data to Aus coastline
```{r}
wdpa_crs <- "+proj=cea +lon_0=0 +lat_ts=30 +x_0=0 +y_0=0 +datum=WGS84 +ellps=WGS84 +units=m +no_defs"

aus <- st_transform(ozmaps::ozmap_country, crs = st_crs(wdpa_crs))

aus_pa_data <-
  aus_pa_data %>%
  filter(MARINE == "terrestrial") %>%
  st_intersection(aus) 

head(aus_pa_data)

# recalculate area of each protected area
aus_pa_data <- 
  aus_pa_data %>%
  mutate(AREA_KM2 = as.numeric(st_area(.)) * 1e-6)

```

## plotting
```{r}
# reproject data for visualisation
aus_pa_data <- st_transform(aus_pa_data, 4326)
# Transform aus projection back
aus <- st_transform(ozmaps::ozmap_country, 4326)

# Base map 
base_map <- ggplot() + 
  geom_sf(data = aus, fill = NA, colour = "black") + 
  theme_minimal()

# terrestrial PA's
base_map +
  geom_sf(data = aus_pa_data,
          aes(geometry = geometry),
          colour = "#609966",
          fill = "lightgreen") +
  coord_sf(c(110, 155)) +
  theme_minimal() |> 
  theme(legend.position = "none")


```

## overlap with hotspots
```{r}
merged_geo <- rast(here("data/protected_areas/bias_corrected_hotspots_spatraster.tif"))

# hotspots (95th percentiles)
rich_q95 <- global(merged_geo[["richness_sampbias_corrected"]], quantile, probs = 0.95, na.rm = TRUE)[1, 1]
merged_geo$rich_perc <- merged_geo[["richness_sampbias_corrected"]] > rich_q95

WE_q95 <- global(merged_geo[["WE_sampbias_corrected"]], quantile, probs = 0.95, na.rm = TRUE)[1, 1]
merged_geo$WE_perc <- merged_geo[["WE_sampbias_corrected"]] > WE_q95


v <- vect(aus_pa_data)
v <- project(v, merged_geo)

aus_pa_raster <- rasterize(v, merged_geo, touches = TRUE)

values(aus_pa_raster)[is.nan(values(aus_pa_raster))] <- NA


# getting cells where hotspots overlap with PA's
overlap <- (!is.na(aus_pa_raster)) & (merged_geo[["rich_perc"]] > 0)
names(overlap) <- "richness"
overlap$WE <- (!is.na(aus_pa_raster)) & (merged_geo[["WE_perc"]] > 0)


# converting to data frame for plotting
aus_pa_raster_df <- as.data.frame(aus_pa_raster, xy = TRUE, na.rm = TRUE)
merged_geo_df <- as.data.frame(merged_geo, xy = TRUE, na.rm = TRUE)
overlap_df <- as.data.frame(overlap, xy = TRUE, na.rm = TRUE)


freq(overlap$richness)[2,3]/freq(merged_geo$rich_perc)[2,3]*100 # percentage of richness hotspots within PA's
freq(overlap$WE)[2,3]/freq(merged_geo$WE_perc)[2,3]*100 # percentage of WE hotspots within PA's


ggplot() +
  geom_sf(data = ozmap_states, fill = "white") + 
  geom_tile(data = subset(merged_geo_df, rich_perc), aes(x=x, y=y), fill = "red", col = NA) +
  geom_tile(data = aus_pa_raster_df, aes(x=x, y=y), fill = "grey", col = NA) +
  geom_tile(data = subset(overlap_df, richness), aes(x=x, y=y), fill = "darkgreen", col = NA) +
  geom_sf(data = ozmap_states, fill = NA, colour = "black") + 
  coord_sf(xlim = c(110, 155),
          ylim = c(-10, -45)) +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot() +
  geom_sf(data = ozmap_states, fill = "white") + 
  geom_tile(data = subset(merged_geo_df, WE_perc), aes(x=x, y=y), fill = "red", col = NA) +
  geom_tile(data = aus_pa_raster_df, aes(x=x, y=y), fill = "grey", col = NA) +
  geom_tile(data = subset(overlap_df, WE), aes(x=x, y=y), fill = "darkgreen", col = NA) +
  geom_sf(data = ozmap_states, fill = NA, colour = "black") + 
  coord_sf(xlim = c(110, 155),
          ylim = c(-10, -45)) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

## overlap with hotspots - short range
```{r}
merged_geo_sr <- rast(here("data/protected_areas/sr_bias_corrected_hotspots_spatraster.tif"))

# hotspots (95th percentiles)
rich_q95_sr <- global(merged_geo_sr[["richness_sr_sampbias_corrected"]], quantile, probs = 0.95, na.rm = TRUE)[1, 1]
merged_geo_sr$rich_perc <- merged_geo_sr[["richness_sr_sampbias_corrected"]] > rich_q95_sr

WE_q95_sr <- global(merged_geo_sr[["WE_sr_sampbias_corrected"]], quantile, probs = 0.95, na.rm = TRUE)[1, 1]
merged_geo_sr$WE_perc <- merged_geo_sr[["WE_sr_sampbias_corrected"]] > WE_q95_sr


v <- vect(aus_pa_data)
v <- project(v, merged_geo_sr)

aus_pa_raster <- rasterize(v, merged_geo_sr, touches = TRUE)

values(aus_pa_raster)[is.nan(values(aus_pa_raster))] <- NA


# getting cells where hotspots overlap with PA's
overlap_sr <- (!is.na(aus_pa_raster)) & (merged_geo_sr[["rich_perc"]] > 0)
names(overlap_sr) <- "richness"
overlap_sr$WE <- (!is.na(aus_pa_raster)) & (merged_geo_sr[["WE_perc"]] > 0)


# converting to data frame for plotting
aus_pa_raster_df <- as.data.frame(aus_pa_raster, xy = TRUE, na.rm = TRUE)
merged_geo_sr_df <- as.data.frame(merged_geo_sr, xy = TRUE, na.rm = TRUE)
overlap_sr_df <- as.data.frame(overlap_sr, xy = TRUE, na.rm = TRUE)


freq(overlap_sr$richness)[2,3]/freq(merged_geo_sr$rich_perc)[2,3]*100 # percentage of richness hotspots within PA's
freq(overlap_sr$WE)[2,3]/freq(merged_geo_sr$WE_perc)[2,3]*100 # percentage of WE hotspots within PA's


ggplot() +
  geom_sf(data = ozmap_states, fill = "white") + 
  geom_tile(data = subset(merged_geo_sr_df, rich_perc), aes(x=x, y=y), fill = "red", col = NA) +
  geom_tile(data = aus_pa_raster_df, aes(x=x, y=y), fill = "grey", col = NA) +
  geom_tile(data = subset(overlap_sr_df, richness), aes(x=x, y=y), fill = "darkgreen", col = NA) +
  geom_sf(data = ozmap_states, fill = NA, colour = "black") + 
  coord_sf(xlim = c(110, 155),
          ylim = c(-10, -45)) +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot() +
  geom_sf(data = ozmap_states, fill = "white") + 
  geom_tile(data = subset(merged_geo_sr_df, WE_perc), aes(x=x, y=y), fill = "red", col = NA) +
  geom_tile(data = aus_pa_raster_df, aes(x=x, y=y), fill = "grey", col = NA) +
  geom_tile(data = subset(overlap_sr_df, WE), aes(x=x, y=y), fill = "darkgreen", col = NA) +
  geom_sf(data = ozmap_states, fill = NA, colour = "black") + 
  coord_sf(xlim = c(110, 155),
          ylim = c(-10, -45)) +
  theme_minimal() +
  theme(legend.position = "bottom")
```



# Expert data only

## overlap with hotspots
```{r}
merged_geo_ex <- rast(here("data/protected_areas/ex_bias_corrected_hotspots_spatraster.tif"))

# hotspots (95th percentiles)
rich_q95_ex <- global(merged_geo_ex[["richness_ex_sampbias_corrected"]], quantile, probs = 0.95, na.rm = TRUE)[1, 1]
merged_geo_ex$rich_perc <- merged_geo_ex[["richness_ex_sampbias_corrected"]] > rich_q95_ex

WE_q95_ex <- global(merged_geo_ex[["WE_ex_sampbias_corrected"]], quantile, probs = 0.95, na.rm = TRUE)[1, 1]
merged_geo_ex$WE_perc <- merged_geo_ex[["WE_ex_sampbias_corrected"]] > WE_q95_ex


v <- vect(aus_pa_data)
v <- project(v, merged_geo_ex)

aus_pa_raster <- rasterize(v, merged_geo_ex, touches = TRUE)

values(aus_pa_raster)[is.nan(values(aus_pa_raster))] <- NA


# getting cells where hotspots overlap with PA's
overlap_ex <- (!is.na(aus_pa_raster)) & (merged_geo_ex[["rich_perc"]] > 0)
names(overlap_ex) <- "richness"
overlap_ex$WE <- (!is.na(aus_pa_raster)) & (merged_geo_ex[["WE_perc"]] > 0)


# converting to data frame for plotting
aus_pa_raster_df <- as.data.frame(aus_pa_raster, xy = TRUE, na.rm = TRUE)
merged_geo_ex_df <- as.data.frame(merged_geo_ex, xy = TRUE, na.rm = TRUE)
overlap_ex_df <- as.data.frame(overlap_ex, xy = TRUE, na.rm = TRUE)


freq(overlap_ex$richness)[2,3]/freq(merged_geo_ex$rich_perc)[2,3]*100 # percentage of richness hotspots within PA's
freq(overlap_ex$WE)[2,3]/freq(merged_geo_ex$WE_perc)[2,3]*100 # percentage of WE hotspots within PA's


ggplot() +
  geom_sf(data = ozmap_states, fill = "white") + 
  geom_tile(data = subset(merged_geo_ex_df, rich_perc), aes(x=x, y=y), fill = "red", col = NA) +
  geom_tile(data = aus_pa_raster_df, aes(x=x, y=y), fill = "grey", col = NA) +
  geom_tile(data = subset(overlap_ex_df, richness), aes(x=x, y=y), fill = "darkgreen", col = NA) +
  geom_sf(data = ozmap_states, fill = NA, colour = "black") + 
  coord_sf(xlim = c(110, 155),
          ylim = c(-10, -45)) +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot() +
  geom_sf(data = ozmap_states, fill = "white") + 
  geom_tile(data = subset(merged_geo_ex_df, WE_perc), aes(x=x, y=y), fill = "red", col = NA) +
  geom_tile(data = aus_pa_raster_df, aes(x=x, y=y), fill = "grey", col = NA) +
  geom_tile(data = subset(overlap_ex_df, WE), aes(x=x, y=y), fill = "darkgreen", col = NA) +
  geom_sf(data = ozmap_states, fill = NA, colour = "black") + 
  coord_sf(xlim = c(110, 155),
          ylim = c(-10, -45)) +
  theme_minimal() +
  theme(legend.position = "bottom")
```

## overlap with hotspots - short range
```{r}
merged_geo_sr_ex <- rast(here("data/protected_areas/sr_ex_bias_corrected_hotspots_spatraster.tif"))

# hotspots (95th percentiles)
rich_q95_sr_ex <- global(merged_geo_sr_ex[["richness_sr_ex_sampbias_corrected"]], quantile, probs = 0.95, na.rm = TRUE)[1, 1]
merged_geo_sr_ex$rich_perc <- merged_geo_sr_ex[["richness_sr_ex_sampbias_corrected"]] > rich_q95_sr_ex

WE_q95_sr_ex <- global(merged_geo_sr_ex[["WE_sr_ex_sampbias_corrected"]], quantile, probs = 0.95, na.rm = TRUE)[1, 1]
merged_geo_sr_ex$WE_perc <- merged_geo_sr_ex[["WE_sr_ex_sampbias_corrected"]] > WE_q95_sr_ex


v <- vect(aus_pa_data)
v <- project(v, merged_geo_sr)

aus_pa_raster <- rasterize(v, merged_geo_sr_ex, touches = TRUE)

values(aus_pa_raster)[is.nan(values(aus_pa_raster))] <- NA


# getting cells where hotspots overlap with PA's
overlap_sr_ex <- (!is.na(aus_pa_raster)) & (merged_geo_sr_ex[["rich_perc"]] > 0)
names(overlap_sr_ex) <- "richness"
overlap_sr_ex$WE <- (!is.na(aus_pa_raster)) & (merged_geo_sr_ex[["WE_perc"]] > 0)


# converting to data frame for plotting
aus_pa_raster_df <- as.data.frame(aus_pa_raster, xy = TRUE, na.rm = TRUE)
merged_geo_sr_ex_df <- as.data.frame(merged_geo_sr_ex, xy = TRUE, na.rm = TRUE)
overlap_sr_ex_df <- as.data.frame(overlap_sr_ex, xy = TRUE, na.rm = TRUE)


freq(overlap_sr_ex$richness)[2,3]/freq(merged_geo_sr_ex$rich_perc)[2,3]*100 # percentage of richness hotspots within PA's
freq(overlap_sr_ex$WE)[2,3]/freq(merged_geo_sr_ex$WE_perc)[2,3]*100 # percentage of WE hotspots within PA's


ggplot() +
  geom_sf(data = ozmap_states, fill = "white") + 
  geom_tile(data = subset(merged_geo_sr_ex_df, rich_perc), aes(x=x, y=y), fill = "red", col = NA) +
  geom_tile(data = aus_pa_raster_df, aes(x=x, y=y), fill = "grey", col = NA) +
  geom_tile(data = subset(overlap_sr_ex_df, richness), aes(x=x, y=y), fill = "darkgreen", col = NA) +
  geom_sf(data = ozmap_states, fill = NA, colour = "black") + 
  coord_sf(xlim = c(110, 155),
          ylim = c(-10, -45)) +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot() +
  geom_sf(data = ozmap_states, fill = "white") + 
  geom_tile(data = subset(merged_geo_sr_ex_df, WE_perc), aes(x=x, y=y), fill = "red", col = NA) +
  geom_tile(data = aus_pa_raster_df, aes(x=x, y=y), fill = "grey", col = NA) +
  geom_tile(data = subset(overlap_sr_ex_df, WE), aes(x=x, y=y), fill = "darkgreen", col = NA) +
  geom_sf(data = ozmap_states, fill = NA, colour = "black") + 
  coord_sf(xlim = c(110, 155),
          ylim = c(-10, -45)) +
  theme_minimal() +
  theme(legend.position = "bottom")
```


# Human observation data only

## overlap with hotspots
```{r}
merged_geo_hum_obs <- rast(here("data/protected_areas/hum_obs_bias_corrected_hotspots_spatraster.tif"))

# hotspots (95th percentiles)
rich_q95_hum_obs <- global(merged_geo_hum_obs[["richness_hum_obs_sampbias_corrected"]], quantile, probs = 0.95, na.rm = TRUE)[1, 1]
merged_geo_hum_obs$rich_perc <- merged_geo_hum_obs[["richness_hum_obs_sampbias_corrected"]] > rich_q95_hum_obs

WE_q95_hum_obs <- global(merged_geo_hum_obs[["WE_hum_obs_sampbias_corrected"]], quantile, probs = 0.95, na.rm = TRUE)[1, 1]
merged_geo_hum_obs$WE_perc <- merged_geo_hum_obs[["WE_hum_obs_sampbias_corrected"]] > WE_q95_hum_obs


v <- vect(aus_pa_data)
v <- project(v, merged_geo_hum_obs)

aus_pa_raster <- rasterize(v, merged_geo_hum_obs, touches = TRUE)

values(aus_pa_raster)[is.nan(values(aus_pa_raster))] <- NA


# getting cells where hotspots overlap with PA's
overlap_hum_obs <- (!is.na(aus_pa_raster)) & (merged_geo_hum_obs[["rich_perc"]] > 0)
names(overlap_hum_obs) <- "richness"
overlap_hum_obs$WE <- (!is.na(aus_pa_raster)) & (merged_geo_hum_obs[["WE_perc"]] > 0)


# converting to data frame for plotting
aus_pa_raster_df <- as.data.frame(aus_pa_raster, xy = TRUE, na.rm = TRUE)
merged_geo_hum_obs_df <- as.data.frame(merged_geo_hum_obs, xy = TRUE, na.rm = TRUE)
overlap_hum_obs_df <- as.data.frame(overlap_hum_obs, xy = TRUE, na.rm = TRUE)


freq(overlap_hum_obs$richness)[2,3]/freq(merged_geo_hum_obs$rich_perc)[2,3]*100 # percentage of richness hotspots within PA's
freq(overlap_hum_obs$WE)[2,3]/freq(merged_geo_hum_obs$WE_perc)[2,3]*100 # percentage of WE hotspots within PA's


ggplot() +
  geom_sf(data = ozmap_states, fill = "white") + 
  geom_tile(data = subset(merged_geo_hum_obs_df, rich_perc), aes(x=x, y=y), fill = "red", col = NA) +
  geom_tile(data = aus_pa_raster_df, aes(x=x, y=y), fill = "grey", col = NA) +
  geom_tile(data = subset(overlap_hum_obs_df, richness), aes(x=x, y=y), fill = "darkgreen", col = NA) +
  geom_sf(data = ozmap_states, fill = NA, colour = "black") + 
  coord_sf(xlim = c(110, 155),
          ylim = c(-10, -45)) +
  theme_minimal() +
  theme(legend.position = "bottom")

ggplot() +
  geom_sf(data = ozmap_states, fill = "white") + 
  geom_tile(data = subset(merged_geo_hum_obs_df, WE_perc), aes(x=x, y=y), fill = "red", col = NA) +
  geom_tile(data = aus_pa_raster_df, aes(x=x, y=y), fill = "grey", col = NA) +
  geom_tile(data = subset(overlap_hum_obs_df, WE), aes(x=x, y=y), fill = "darkgreen", col = NA) +
  geom_sf(data = ozmap_states, fill = NA, colour = "black") + 
  coord_sf(xlim = c(110, 155),
          ylim = c(-10, -45)) +
  theme_minimal() +
  theme(legend.position = "bottom")
```


